// Code generated by "stringer -type=ConnectionErrorType -linecomment"; DO NOT EDIT.

package websocket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientNotFound-0]
}

const _ConnectionErrorType_name = "could not find client"

var _ConnectionErrorType_index = [...]uint8{0, 21}

func (i ConnectionErrorType) String() string {
	if i < 0 || i >= ConnectionErrorType(len(_ConnectionErrorType_index)-1) {
		return "ConnectionErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionErrorType_name[_ConnectionErrorType_index[i]:_ConnectionErrorType_index[i+1]]
}
