metrics:
    enabled: true
    # Enable runtime stats (memory, threads)
    runtime: true
    file:
        # Log metrics every minute to a file
        enabled: true
        filename: "metrics.log"
        # Write to log asynchronously
        async: true
        # Configure file rotation (optional)
        rotate:
            enabled: true
            # Max number of MB in a file before rotating
            maxsize: 100 # MB
            # Max number of old files to retain -- 0 to disable
            maxcount: 0
            # Max number of days (24-hours) to retain old files -- 0 to disable
            maxage: 0
            # Rotate an existing file and start fresh
            rotate_existing: true
            # Compress with gzip (.gz) on rotate
            compress: true
    http:
        # Metrics exposed through HTTP server at localhost:<port>/debug/metrics
        enabled: false
        port: 8411
